// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiMvc.Data;

#nullable disable

namespace ReversiMvc.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20220323135041_AddDefaultUser")]
partial class AddDefaultUser
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("NormalizedName")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("NormalizedName")
                .IsUnique()
                .HasDatabaseName("RoleNameIndex");

            b.ToTable("AspNetRoles", (string)null);

            b.HasData(
                new
                {
                    Id = "37186721-a6e7-418f-8a56-1c3b6596264f",
                    ConcurrencyStamp = "c62341c3-6fbe-4e1f-bb56-fd8de73d248d",
                    Name = "Admin",
                    NormalizedName = "ADMIN"
                },
                new
                {
                    Id = "01b92546-0595-43fb-b74b-63041cec49c3",
                    ConcurrencyStamp = "0550b4cb-2025-4b6e-98bd-e3cf6ad4e3da",
                    Name = "Mediator",
                    NormalizedName = "MEDIATOR"
                });
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("ClaimType")
                .HasColumnType("TEXT");

            b.Property<string>("ClaimValue")
                .HasColumnType("TEXT");

            b.Property<string>("RoleId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("RoleId");

            b.ToTable("AspNetRoleClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<int>("AccessFailedCount")
                .HasColumnType("INTEGER");

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("TEXT");

            b.Property<string>("Email")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<bool>("EmailConfirmed")
                .HasColumnType("INTEGER");

            b.Property<bool>("LockoutEnabled")
                .HasColumnType("INTEGER");

            b.Property<DateTimeOffset?>("LockoutEnd")
                .HasColumnType("TEXT");

            b.Property<string>("NormalizedEmail")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("NormalizedUserName")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("PasswordHash")
                .HasColumnType("TEXT");

            b.Property<string>("PhoneNumber")
                .HasColumnType("TEXT");

            b.Property<bool>("PhoneNumberConfirmed")
                .HasColumnType("INTEGER");

            b.Property<string>("SecurityStamp")
                .HasColumnType("TEXT");

            b.Property<bool>("TwoFactorEnabled")
                .HasColumnType("INTEGER");

            b.Property<string>("UserName")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("NormalizedEmail")
                .HasDatabaseName("EmailIndex");

            b.HasIndex("NormalizedUserName")
                .IsUnique()
                .HasDatabaseName("UserNameIndex");

            b.ToTable("AspNetUsers", (string)null);

            b.HasData(
                new
                {
                    Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                    AccessFailedCount = 0,
                    ConcurrencyStamp = "52005321-457a-4d4d-988a-1e774c23ee0e",
                    Email = "admin@nimda.com",
                    EmailConfirmed = true,
                    LockoutEnabled = false,
                    NormalizedEmail = "ADMIN@NIMDA.COM",
                    NormalizedUserName = "ADMIN@NIMDA.COM",
                    PasswordHash = "AQAAAAEAACcQAAAAEIaf6sraeJdePw02NtvgvqENYmRJeDyvmfoAv1QAKN1jYnla2WoZhBr6Aj/EoOyGMQ==",
                    PhoneNumberConfirmed = false,
                    SecurityStamp = "",
                    TwoFactorEnabled = false,
                    UserName = "admin@nimda.com"
                });
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("ClaimType")
                .HasColumnType("TEXT");

            b.Property<string>("ClaimValue")
                .HasColumnType("TEXT");

            b.Property<string>("UserId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider")
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<string>("ProviderKey")
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<string>("ProviderDisplayName")
                .HasColumnType("TEXT");

            b.Property<string>("UserId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("LoginProvider", "ProviderKey");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserLogins", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId")
                .HasColumnType("TEXT");

            b.Property<string>("RoleId")
                .HasColumnType("TEXT");

            b.HasKey("UserId", "RoleId");

            b.HasIndex("RoleId");

            b.ToTable("AspNetUserRoles", (string)null);

            b.HasData(
                new
                {
                    UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                    RoleId = "37186721-a6e7-418f-8a56-1c3b6596264f"
                });
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId")
                .HasColumnType("TEXT");

            b.Property<string>("LoginProvider")
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<string>("Value")
                .HasColumnType("TEXT");

            b.HasKey("UserId", "LoginProvider", "Name");

            b.ToTable("AspNetUserTokens", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
