// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiMvc.Data;

#nullable disable

namespace ReversiMvc.Data.Migrations;

[DbContext(typeof(ReversiDbContext))]
partial class ReversiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("ReversiMvc.Models.Entities.PlayerEntity", b =>
        {
            b.Property<string>("Guid")
                .HasColumnType("nvarchar(450)");

            b.Property<int>("Draws")
                .HasColumnType("int");

            b.Property<int>("Losses")
                .HasColumnType("int");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<int>("Victories")
                .HasColumnType("int");

            b.HasKey("Guid");

            b.ToTable("Players");
        });
#pragma warning restore 612, 618
    }
}
